### ISSUE TITLE
Special characters converted in mailto links with variables

### ISSUE THREAD

**Issue by sushidave** [skinofthesoul/grav-plugin-antispam#20]
Hi, 
Thank you for sharing your great plugin with the community.

It seems that it processes some of the special characters (?, &, :, /) by mistake in mailto links that contain variables:

**Example a)**

Code in the Twig template:
`<a href="mailto:info@domain.com?subject=&body={{ page.url(true) }}" title="Share by e-mail">E-mail</a>"`

After processing:
`<a href="mailto:info@domain.com0subject0body0https000example.org0en" title="Share by e-mail" target="_blank">E-mail</a>"`

**Example b)**

Code in the Twig template:
`<a href="mailto:?subject=&body={{ page.url(true) }}" title="Share by e-mail">E-mail</a>"`

After processing:
`<a href="mailto:@subject@@body@https@@@example.org@en" title="Share by e-mail" target="_blank">E-mail</a>"`

Also, the new character replacing those special characters is a different one on each page reload.

Can you help please?

Grav version: 1.7.31
Plugin version: 1.5.2
Configuration:
enabled: true
target: true
change_on_output: true

**Comment by skinofthesoul** [comment]
Hey there, thanks for letting me know! This isn't hard to fix I think, I hope I can fit it in next week. I'll let you know.

**Comment by sushidave** [comment]
Hi @skinofthesoul  
It's probably a bit of regex work. Thanks a lot for looking into it. 
Have a good weekend! :)

**Comment by skinofthesoul** [comment]
I finally got around to fixing this, and it turned out it *wasn't* the regex…! I only realised that after knotting up my brain of course. Anyway v1.5.3 should let you use parameters, and I also fixed some minor nonsense while I was at it. :-)

**Comment by sushidave** [comment]
@skinofthesoul 
Thank you for your effort, Anna.
It seems that Grav has yet to pick up the new version for its plug-in repository. I'll report back to you once it's there.
Have a good weekend!

**Comment by sushidave** [comment]
Hi @skinofthesoul,
The new release seems to have fixed some of the special characters. Others still appear in the body value.
`<a href="mailto:?subject=&body=https@@@example.org@en" title="Share by e-mail" target="_blank">E-mail</a>"`
Could you please recheck?

**Comment by skinofthesoul** [comment]
Hmm, what was your input?

**Comment by sushidave** [comment]
Hey @skinofthesoul , the value of the body was the URL only, e.g. https://example.org/en.

**Comment by skinofthesoul** [comment]
… I reckon you mean an email address input? Like test@example.com?

I have a development site with a whole bunch of different inputs, and they all work fine now, including the ones with title attributes and subject or body input. If you're sure it's not a cache issue (with either the Grav cache(s) or your browser cache) – that's tripped me up so many times –, please post your markdown source and the output it produces so I can try to replicate the problem.

**Comment by sushidave** [comment]
@skinofthesoul 
Thanks for your answer and sorry that it was not clear.

I was referring to the value of the body variable. It only contains a URL. In our case the value of the email address is empty (= to be added by the user before sending). 

The use case is a set of social share buttons on a website where one of the buttons enables people to share the URL of the page by email.

Code example:
```
<div class="social-share">
  <ul class="inline-list tm-icons jl-grid">
	<li class="email"><a href="mailto:?subject=&body={{ page.url(true) }}" title="Share by e-mail"><i class="jl-icon-button fa fa-envelope-o"></i></a></li>
	<li class="sample-network">(...)</li>
	(...)
  </ul>
</div>
```

Output:
```
<div class="social-share">
   <ul class="inline-list tm-icons jl-grid">
	<li class="email"><script type="text/javascript" language="javascript">
// Email obfuscator script 2.1 by Tim Williams, University of Arizona
// Random encryption key feature by Andrew Moulden, Site Engineering Ltd
// PHP version coded by Ross Killen, Celtic Productions Ltd
// This code is freeware provided these six comment lines remain intact
// A wizard to generate this code is at http://www.jottings.com/obfuscator/
// The PHP code may be obtained from http://www.celticproductions.net/


coded = "(...coded_string...)"
 key = "RJyYdBW=kX8CMAGo3lOez7?rjntS&.TimwENQPb2FhHc-I_DVpv1s5a04uxfq6gLZUK9@"
 shift=coded.length
 link=""
 for (i=0; i<coded.length; i++) {
 if (key.indexOf(coded.charAt(i))==-1) {
 ltr = coded.charAt(i)
 link += (ltr)
 }
 else { 
 ltr = (key.indexOf(coded.charAt(i))-
      shift+key.length) % key.length
 link += (key.charAt(ltr))
 }
 }
document.write("<a href='mailto:"+link+"' target='_blank' title=\"Share by e-mail\">"+'<i class="jl-icon-button fa fa-envelope-o"></i>'+"</a>")

</script><noscript>[email address is javascript encrypted]</noscript></li>
	<li class="sample-network">(...)</li>
	(...)
  </ul>
</div>
```
The problem remains after emptying the cache of Grav and the browser. 

I hope this helps you in finding the cause. Thanks for looking into this. Please advise if you need further details.

**Comment by skinofthesoul** [comment]
Ah, I see. The list of encodeable characters was missing slashes and colons. I've fixed it in the next version, should be ok now!

**Comment by sushidave** [comment]
Dear @skinofthesoul , thank you very much for the fix. Once the new version is available in the backend I will report back to you.
Meanwhile, I found another thing for which I am going to create a separate issue.

**Comment by sushidave** [comment]
@skinofthesoul I'm happy to confirm that it works now. Thank you!
